const turfTextBody =
    "Join PlaySports to explore the largest network of sports facilities and to connect with the sports community near to you. Games is a physical or mental activity or contest that has rules and that people do for pleasure.Turf is comprised of synthetic fibers that are designed to look like grass. While the appearance isn't an exact replica of grass, it's able to appear similar to grass while providing homeowners with a number of unique benefit.The fibers are typically made from nylon, polypropylene or polyethylene and are connected to a backing material. The base material, also called infill, consists of one or more granular materials that are worked in between the fibers during the installation process.";
const footballTextBody =
    "There are more than 265 million players in the world, and an estimated 4 billion people are actively watching the sport from time to time, which without a doubt makes it the most popular sport in the world.It is widely acknowledged that it was England which transitioned the game of Football into the game we know today. The English are also credited with recording the first uniform set of rules for the sport, which include forbidding tripping opponents and touching the ball with hands (with the obvious exception of the goalkeeper).Football is one of the oldest known sports known to humankind with records found dating over 2,000 years in China.";
const badmintonTextBody =
    "Badminton is a type of racket sport that is either played indoors by individuals (singles) or a team of two (doubles). Badminton was developed in British India from a children’s game called 'battledore and shuttlecock'. Badminton was called “Poona” in India in the 18th century. The British Army who were assigned there took the game back to the UK and introduced it to their colleagues. The Duke of Beaufort launched Badminton officially in 1873.";
const cricketTextBody =
    "Cricket is a good sport for developing overall fitness, stamina and hand–eye coordination. Cricket uses a hard ball, so protective gear should be worn to avoid injury. The first reference to cricket being played as an adult sport was in 1611, and in the same year, a dictionary defined cricket as a boys' game.";
const clockTextBody =
    "THERE is a time for each year to end, and a time for each year to begin,'' to paraphrase Ecclesiastes. This is the time when we are most aware of time. We can't control it, we can't delay or stop it, we can only be aware that time is pitiless. Yet kindly, and inevitable. It is only in certain games that we deal artificially with time.";
const emailText = "Email";
const passwordText = "Password";
